version: '3.8'

services:
  nginx:
    container_name: "nginx"
    networks:
      - inception
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - wordpress:/var/www/html/wordpress

  mariadb:
    container_name: "mariadb"
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: none
      o : bind
      device : /home/gd-harco/data/wordpress
  mariadb:
    name: "mariadb"
    driver: local
    driver_opts:
      type: none
      o : bind
      device : /home/gd-harco/data/mariadb

networks:
  inception:
    driver: bridge

    