version: '3.8'
services:

  #nginx server
  nginx:
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - inception
    volumes:
      - WordPress:/var/www/html

  #Wordpress &PHP
  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - inception
    volumes:
      - WordPress:/var/www/html

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    networks:
      - inception
    volumes:
      - DataBase:/var/lib/mysql


volumes:
  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/gd-harco/data/wordpress
  DataBase:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/gd-harco/data/mariadb

networks:
  inception:
    driver: bridge