version: '3.8'

services:

#  WORDPRESS & PHP
  wordpress:
    depends_on:
      - mariadb
    env_file:
      - .env
    container_name: "wordpress"
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - wordpress:/var/www/html/wordpress

  nginx:
    container_name: "nginx"
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - wordpress:/var/www/html/wordpress

  mariadb:
    container_name: "mariadb"
    env_file:
      - .env
    networks:
      - inception
    build:
      context: requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        USER_PSSWD: ${USER_PSSWD}
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: none
      o : bind
      device : /home/gd-harco/data/wordpress
  mariadb:
    name: "mariadb"
    driver: local
    driver_opts:
      type: none
      o : bind
      device : /home/gd-harco/data/mariadb

networks:
  inception:
    driver: bridge

    