version: '3'

services:
  nginx:
    container_name: "nginx"
    networks:
      - inception
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure


networks:
  inception:
    driver: bridge