version: '3.8'
services:

  #nginx server
  nginx:
    container_name: nginx
    ports:
      - 443:443
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - WordPress:/var/www/html

volumes:
  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/gd-harco/data/wordpress
