version: '3.8'
services:

  #nginx server
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - inception
    volumes:
      - WordPress:/var/www/html

  #Wordpress &PHP
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - inception
    volumes:
      - WordPress:/var/www/html
    expose:
      - 9000

volumes:
  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/gd-harco/data/wordpress

networks:
  inception:
    driver: bridge
